cat << 'EOF' > training-1.sh
#!/bin/bash

aws sagemaker create-training-job --training-job-name 1s --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.2xlarge,InstanceCount=5,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.2xlarge,InstanceCount=5,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.2xlarge,InstanceCount=5,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.2xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 1s --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c6i.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 2s --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 5s --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 4s --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
aws sagemaker create-training-job --training-job-name 3s --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m4.4xlarge,InstanceCount=3,VolumeSizeInGB=10,KeepAlivePeriodInSeconds=60 --stopping-condition MaxRuntimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/hjhj/
sleep 180
EOF
