cat << 'EOF' > training-2.sh
#!/bin/bash


aws sagemaker create-training-job --training-job-name 1a --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region us-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region us-east-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region us-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region us-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region af-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-southeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-southeast-4 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-4.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.2xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-southeast-4 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-4.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-southeast-4 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-4.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-northeast-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
aws sagemaker create-training-job --training-job-name 3a --region ap-northeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-southeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-southeast-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ap-northeast-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ca-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region ca-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.ca-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-west-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-west-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-west-3 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.2xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-south-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-south-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-north-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region eu-central-2 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.eu-central-2.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region me-south-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-south-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region me-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.me-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region il-central-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.il-central-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 1a --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m6i.8xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 2a --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.m5.4xlarge,InstanceCount=4,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
aws sagemaker create-training-job --training-job-name 3a --region sa-east-1 --algorithm-specification TrainingImage=$ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/uyah:latest,TrainingInputMode=Pipe --role-arn $ROLE_ARN --resource-config InstanceType=ml.c5.4xlarge,InstanceCount=2,VolumeSizeInGB=10 --stopping-condition MaxRuntimeInSeconds=432000,MaxWaitTimeInSeconds=432000 --output-data-config S3OutputPath=s3://$ACCOUNT_ID/uyah/ --enable-managed-spot-training
sleep 180
EOF